### PR TITLE
Added --webpack option to "convert".

### PR DESCRIPTION
**Pull request by mperrando**

### CODE REVIEW

**Comment by jhilden** [comment]
thanks for that PR as well.  I haven't used Rails 5 + webpack yet, but it seems reasonable to me.

Could you be so kind to add an "Options" section to the README and explain what the `--wepack` is for?  In addition, while you are at it, could you maybe even bump the version and update the CHANGELOG, so I can publish a new release?

**Comment by jhilden** [comment]
awesome :tada:

**Comment by mperrando** [comment]
Sorry, but I was still refining the README. My bad that I was pushing on the PR branch.

**Comment by jhilden** [comment]
ok, sorry for being so hasty.  just let me know when you are done with your changes and we will figure it out

**Comment by mperrando** [comment]
I'm done with commit fdab7848b4e06478b6428039214d1d948f10ba11.

Sorry for the messy branch.

**Comment by jhilden** [comment]
I cherry-picked that commit to master.  I think everything should be fine now, or?

The new release has also already been published.

Thank you so much for your contribution again.

**Pull request merged**
